services:
  - type: web
    name: connect-sphere-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: RESEND_AUDIENCE_ID
        sync: false
